#!/bin/sh

# Record a map of commit changes, so we can fix up the svn revision map
# It's easier to just store the svn revs as honest-to-goodness refs,
# but filter-branch's performance with that many refs is ... unfortunate
COMMIT_MAP=$(pwd)/.git/commit.map
echo '' > $COMMIT_MAP
export COMMIT_MAP
export SVN_REF_DIR=$(pwd)/.git/svn

# strip svk and git-svn noise, retaining tags
git filter-branch \
--tag-name-filter cat \
--msg-filter "git svn-abandon-msg-filter" \
--commit-filter '
n=$( git commit-tree "$@" )
echo "$GIT_COMMIT $n" >> $COMMIT_MAP
echo $n' \
-- --all

# if we laid down any svn version refs, update them
if [ -d .git/svn ]; then
    # Associative arrays in bash are hard.  Let's go shopping
    git-svn-abandon-fix-remapped-svn-refs.pl
fi

rm $COMMIT_MAP

# remove the backup refs
git for-each-ref --format='%(refname)' refs/original/ refs/remotes/svn/ | while read ref; do
    git update-ref -d "$ref"
done

# ditch all pre-conversion objects forcefully
git reflog expire --all --expire=now
git gc --aggressive

git prune
git fsck --full
